import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="min-h-screen content-center bg-cover"
      style={{ backgroundImage: 'url("/assets/violet3.png")' }}
    >
      <body>{children}</body>
    </html>
  );
}
